# Generated by Django 5.2 on 2025-06-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_remove_user_contact_remove_user_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
